### PR TITLE
fixed: respect DESTDIR

### PR DESCRIPTION
**Pull request by akva2**
DESTDIR is used by packaging tools

### CODE REVIEW

**Comment by akva2** [comment]
bugger, scratch this one. tools only set destdir when doing make install so this won't help by itself.

**Comment by akva2** [comment]
okay, got it. this suffices (in combination with packaging file updates).

**Comment by joakim-hove** [comment]
> got it.

Well - I don't really get it. I thought `${CMAKE_INSTALL_PREFIX}` was the way to configure where your installation files should go - or is this an ability to configure a funny prefix path like `/tmp/package-build`? In that case I would assume a similar update must be applied to every single install target?

But sure - thanks I will merge when I am certain I have understood the situation.

**Comment by akva2** [comment]
DESTDIR is an additional layer on top of the prefix. it's a 'prefix for the prefix'.
this is a common mechanism in both autotools and cmake. it's used to install *with* a given prefix, but into another folder. consider the packaging chroot - you don't want to install into the prefix path, but you want to package files with that prefix.

try it manually if you want. make install DESTDIR=/some/dir. you will get /some/dir/usr/local/<files> by default..

**Pull request merged**
