### PR TITLE
Final adjustments

### PR DESCRIPTION
**Pull request by akva2**
- depend on development package in python bindings
- bump versions

Please tag as release/2015.10/final when this has been merged.

### CODE REVIEW

**Comment by joakim-hove** [comment]
OK - I am looking at : #921 now - I assume that also should go to the release branch before we can have a `2015.10/final` tag?

**Comment by akva2** [comment]
no, let's not delay the release for that. the workaround is 6c8ef5c.

**Comment by joakim-hove** [comment]
> let's not delay the release for that

Cool - merging; tag on the way.

**Comment by joakim-hove** [comment]
Tag made.

**Pull request merged**
