### PR TITLE
Added function / method ecl_kw_first_different().

### PR DESCRIPTION
**Pull request by joakim-hove**
Convenience method for testing / comparing to ecl_kw instances.

### CODE REVIEW

**Comment by pgdr** [comment]
Very good, but what is it for?

**Comment by jepebe** [comment]
Side note: '''__get__''' is not the same as '''__getitem__'''. What is the intention behind this method? Is this supposed to be a descriptor?

**Comment by joakim-hove** [comment]
> Side note: __get__ is not the same as __getitem__. What is the intention behind this method? Is this supposed to be a descriptor?

Hehe - this was several years old code; I just unfortunately touched with some white-space changes. It implemented a *class property* - using "Copy & Paste" technology from stackowerflow. Anyway - actually deprecated now.

**Comment by joakim-hove** [comment]
> Very good, but what is it for?

It is for testing of keywords - typicall Opm style:
```
if not kw1.equal( kw2 ):
   sys.exit("Keywords were not identical - first diffrence in index:%d" % kw1.firstDifferent( kw2 ))
```

**Comment by jepebe** [comment]
> Hehe - this was several years old code; I just unfortunately touched with some white-space changes. It implemented a class property - using "Copy & Paste" technology from stackowerflow. Anyway - actually deprecated now.

Nice! :-)

**Comment by pgdr** [comment]
> It is for testing of keywords - typicall Opm style

Will the index of the first deviation be helpful here?

I have reviewed it and consider it ready for merging.

**Comment by joakim-hove** [comment]
> Will the index of the first deviation be helpful here?

Yes - I think that will be valuable input to a more coherent debugging effort.

> I have reviewed it and consider it ready for merging.

Cool - thank you.

**Pull request merged**
