### PR TITLE
Fix debian packaging

### PR DESCRIPTION
**Pull request by akva2**
this caused an empty python binding class and i didn't spot since the file was existing on my local box. thanks to @babrodtk for spotting.

please backport to the 2015.10 release branch.

### CODE REVIEW

**Comment by joakim-hove** [comment]
> please backport to the 2015.10 release branch.

Will - both commits?

**Comment by akva2** [comment]
yes please

**Comment by joakim-hove** [comment]
OK - the "update debian packaging" commit was already there: https://github.com/Ensembles/ert/commit/8fa4b7731c33433110b12fd0853fff42b08c4cf2

**Comment by akva2** [comment]
yeah, i had forgotten to send the backport pr for that earlier..

**Pull request merged**
