### PR TITLE
ERT-904: Possibility to add local obs nodes without time step range

### PR DESCRIPTION
**Pull request by arielalmendral**
The time range in local obs nodes is currently overridden by the input time steps for ES methods. 

Moving away from iterative methods imply that addNodeAndRange() will be discontinued. 

I propose this 'forward compatibility fix' to create nodes with addNode with no time step list specification. 

This is to simplify the localization setup by removing the already unused ranges.

### CODE REVIEW

**Comment by joakim-hove** [comment]
Ready to merge when my comments have been addressed - or argued to be wrong!

**Comment by joakim-hove** [comment]
This currently fails the Statoil internal tests:
```txt
======================================================================
FAIL: test_obs_block_scale_std (tests.ert.enkf.test_enkf_obs.EnKFObsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/jenkins/workspace/ERT-PR-Test/build/python/tests/ert/enkf/test_enkf_obs.py", line 130, in test_obs_block_scale_std
    obs_data.addObsVector( obs_vector )
  File "/var/jenkins/workspace/ERT-PR-Test/build/python/ert/enkf/local_obsdata.py", line 109, in addObsVector
    self.addNode( obs_vector.createLocalObs() )
  File "/var/jenkins/workspace/ERT-PR-Test/build/python/ert/enkf/local_obsdata.py", line 78, in addNode
    assert isinstance(key, str)
AssertionError

======================================================================
FAIL: test_scale_obs (tests.ert.enkf.test_enkf_obs.EnKFObsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/jenkins/workspace/ERT-PR-Test/build/python/tests/ert/enkf/test_enkf_obs.py", line 38, in test_scale_obs
    local_obsdata.addNode( node1 )
  File "/var/jenkins/workspace/ERT-PR-Test/build/python/ert/enkf/local_obsdata.py", line 78, in addNode
    assert isinstance(key, str)
AssertionError

----------------------------------------------------------------------
Ran 6 tests in 30.813s

FAILED (failures=2)
======================================================================
FAIL: test_obs_block_scale_std (tests.ert.enkf.test_enkf_obs.EnKFObsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/jenkins/workspace/ERT-PR-Test/build/python/tests/ert/enkf/test_enkf_obs.py", line 130, in test_obs_block_scale_std
    obs_data.addObsVector( obs_vector )
  File "/var/jenkins/workspace/ERT-PR-Test/build/python/ert/enkf/local_obsdata.py", line 109, in addObsVector
    self.addNode( obs_vector.createLocalObs() )
  File "/var/jenkins/workspace/ERT-PR-Test/build/python/ert/enkf/local_obsdata.py", line 78, in addNode
    assert isinstance(key, str)
AssertionError

======================================================================
FAIL: test_scale_obs (tests.ert.enkf.test_enkf_obs.EnKFObsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/jenkins/workspace/ERT-PR-Test/build/python/tests/ert/enkf/test_enkf_obs.py", line 38, in test_scale_obs
    local_obsdata.addNode( node1 )
  File "/var/jenkins/workspace/ERT-PR-Test/build/python/ert/enkf/local_obsdata.py", line 78, in addNode
    assert isinstance(key, str)
AssertionError
```

**Comment by arielalmendral** [comment]
Thanks for all the comments. Trying to fix the test now. One comment regarding default value: add_all_timesteps = True in addNode. If this flag is true, ERT will step after running the workflow with the following message: 

Abort called from: local_obsdata_node_get_tstep_list (/nr/project/sand/user/ariel/ERT/ert/devel/libenkf/src/local_obsdata_node.c:110) 

Error message: local_obsdata_node_get_tstep_list: internal error: When the all_timestep_active() switch is set to true you can not ASK for timestep


I think there is a logical glitch somewhere...

**Comment by arielalmendral** [comment]
Here is the call stack when add_all_timesteps = True:

Abort called from: local_obsdata_node_get_tstep_list (/nr/project/sand/user/ariel/ERT/ert/devel/libenkf/src/local_obsdata_node.c:110) 

Error message: local_obsdata_node_get_tstep_list: internal error: When the all_timestep_active() switch is set to true you can not ASK for timestep



--------------------------------------------------------------------------------
 #00 ???(..)                                                             in /nr/project/sand/user/ariel/ERT/ert/devel/libert_util/src/util_abort_gnu.c:152
 #01 util_abort__(..)                                                    in /nr/project/sand/user/ariel/ERT/ert/devel/libert_util/src/util_abort_gnu.c:264
 #02 local_obsdata_node_get_tstep_list(..)                               in /nr/project/sand/user/ariel/ERT/ert/devel/libenkf/src/local_obsdata_node.c:112
 #03 obs_vector_scale_std(..)                                            in /nr/project/sand/user/ariel/ERT/ert/devel/libenkf/src/obs_vector.c:656
 #04 enkf_obs_local_scale_std(..)                                        in /nr/project/sand/user/ariel/ERT/ert/devel/libenkf/src/enkf_obs.c:1168
 #05 ffi_call_unix64(..)                                                 in /usr/src/Python-2.7.9/Modules/_ctypes/libffi/src/x86/unix64.S:79
 #06 ffi_call(..)                                                        in /usr/src/Python-2.7.9/Modules/_ctypes/libffi/src/x86/ffi64.c:527
 #07 _ctypes_callproc(..)                                                in /usr/src/Python-2.7.9/Modules/_ctypes/callproc.c:836
 #08 ???(..)                                                             in /usr/src/Python-2.7.9/Modules/_ctypes/_ctypes.c:3976
 #09 PyObject_Call(..)                                                   in ???
 #10 PyEval_EvalFrameEx(..)                                              in ???
 #11 PyEval_EvalFrameEx(..)                                              in ???
 #12 PyEval_EvalCodeEx(..)                                               in ???
 #13 ???? 
 #14 PyObject_Call(..)                                                   in ???
 #15 PyEval_EvalFrameEx(..)                                              in ???
 #16 PyEval_EvalCodeEx(..)                                               in ???
 #17 PyEval_EvalFrameEx(..)                                              in ???
 #18 PyEval_EvalCodeEx(..)                                               in ???
 #19 PyEval_EvalFrameEx(..)                                              in ???
 #20 PyEval_EvalCodeEx(..)                                               in ???
 #21 PyEval_EvalFrameEx(..)                                              in ???
 #22 PyEval_EvalFrameEx(..)                                              in ???
 #23 PyEval_EvalFrameEx(..)                                              in ???
 #24 PyEval_EvalCodeEx(..)                                               in ???
 #25 ???? 
 #26 PyObject_Call(..)                                                   in ???
 #27 ???? 
 #28 PyObject_Call(..)                                                   in ???
 #29 PyEval_CallObjectWithKeywords(..)                                   in ???
 #30 ???? 
 #31 ???(..)                                                             in pthread_create.c:0
 #32 clone(..)                                                           in ??:0
--------------------------------------------------------------------------------

**Comment by joakim-hove** [comment]
OK - try to rebase your work on top of the commit in this PR: https://github.com/Ensembles/ert/pull/906

**Comment by joakim-hove** [comment]
OK - build test failed; fixup coming.

**Pull request merged**
