### PR TITLE
Added reading ANALYSIS_SCALE_DATA

### PR DESCRIPTION
**Pull request by pgdr**
Added reading ANALYSIS_SCALE_DATA flag for STD_ENKF in config file, default to true

### CODE REVIEW

**Comment by joakim-hove** [comment]
OK - this is a good start; but unfortunately there must be some additional double book keeping between the new bool variable and the variable `long option_flags` , i.e. the `option_flags`must still be maintained correctly. That is because the calling scope does a get of the complete option value and checks the scaling bit externally: https://github.com/Ensembles/ert/blob/master/libenkf/src/enkf_main.c#L1027

**Comment by pgdr** [comment]
Okay, so when the flag is set, I should also do
```c
data->option_flags &= (value * ANALYSIS_SCALE_DATA)
```
?

**Comment by joakim-hove** [comment]
> Okay, so when the flag is set, I should also do [...]

Yes; I guess that is the natural way to do it.

**Comment by joakim-hove** [comment]
OK - not really clear to me why this fails on Travis; but when that is fixed I will merge.

**Comment by pgdr** [comment]
For some reason
```c
    analysis_table_type * analysis_table = (analysis_table_type *) dlsym( lib_handle , table_name );
```
fails in `libanalysis/src/analysis_module.c:163`.

I don't really know the cause of it.

**Comment by joakim-hove** [comment]
> For some reason
```C
analysis_table_type * analysis_table = (analysis_table_type *) [...]
```
fails.

No - I disagree. The error message on stderr is a normal module load failure message when we actually test loading of a not correctly configured module. 

The test failure was a normal failure due to missing initialization of the scale flag; an alternative implementation bypassing the whole problem here: #1211.

**Pull request merged**
