### PR TITLE
Added manpage for ecl_summary as requested by Debian policy.

### PR DESCRIPTION
**Pull request by blattms**
This is only a rudimentary manpage from a template produced by help2man.

### CODE REVIEW

**Comment by joakim-hove** [comment]
Very good - thank you. Should the man page be installed also as part of the RedHat packaging?

**Comment by blattms** [comment]
Yes it should. I forgot to cherry-pick that commit, sorr. Should be
added now.

**Comment by joakim-hove** [comment]
> Should be added now.

I was expecting there should be a change in https://github.com/Ensembles/ert/blob/master/redhat/ert.ecl.spec - but maybe not?

**Comment by blattms** [comment]
Did not think about the packages. Will try to add there, too.

**Comment by blattms** [comment]
I do not feel qualified enough to patch the redhat stuff.
Maybe somebody else can tell it that usr/share/man/man1/ecl_summary.1
needs to be part of the package?

**Comment by joakim-hove** [comment]
Fine - merging.

**Pull request merged**
