### PR TITLE
Numpy 3d fixup

### PR DESCRIPTION
**Pull request by joakim-hove**
Fix a minor typo in the `EclGrid.creat3D()` method : #1197

### CODE REVIEW

**Comment by pgdr** [comment]
Should we merge #1196 first, and then rebase this?  I can't see the numpy fix in all the changes...

**Comment by joakim-hove** [comment]
>  I can't see the numpy fix in all the changes...

The numpy fix is in the last commit; it is absolutely trivial and not really related to numpy.

**Comment by pgdr** [comment]
rebase?

**Comment by joakim-hove** [comment]
> rebase?

Done.

**Comment by pgdr** [comment]
Thanks, merged.  This fixes  #1197.

**Pull request merged**
