### PR TITLE
Ert 1059 gui refactor 

### PR DESCRIPTION
**Pull request by joakim-hove**
This is just a minor extension of: #1058

### CODE REVIEW

**Comment by joakim-hove** [comment]
I have just launched gert –v gui-test and got this message in the console. Also, the WPRO option is not available in the Plug-ins

```txt
bash> gert -v gui-test config.ert
The script '/project/res/etc/ERT/workflows/gui-plugins/scripts/wpro.py' caused an error during load:
ImportError: No module named models.mixins.connectorless
```

**Comment by joakim-hove** [comment]
```txt
When I tried running MDA I got:

Traceback (most recent call last):
  File "/project/res/x86_64_RH_6/share/ert/release/gui-test/python/ert_gui/simulation/simulation_panel.py", line 102, in runSimulation
    arguments = self.getSimulationArguments()
  File "/project/res/x86_64_RH_6/share/ert/release/gui-test/python/ert_gui/simulation/simulation_panel.py", line 92, in getSimulationArguments
    return simulation_widget.getSimulationArguments()
  File "/project/res/x86_64_RH_6/share/ert/release/gui-test/python/ert_gui/simulation/multiple_data_assimilation_panel.py", line 106, in getSimulationArguments
    "target_case": self._target_case_model.getValue(),
AttributeError: 'MultipleDataAssimilationPanel' object has no attribute '_target_case_model'
```

**Comment by jepebe** [comment]
> I have just launched gert –v gui-test and got this message in the console. Also, the WPRO option is not available in the Plug-ins

> ```
> bash> gert -v gui-test config.ert
> The script '/project/res/etc/ERT/workflows/gui-plugins/scripts/wpro.py' caused an error during load:
> ImportError: No module named models.mixins.connectorless
> ```

This is WPRO gracefully exploding. :-) WPRO must be refactored in the same way as the other GUI stuff.

**Comment by jepebe** [comment]
> 
When I tried running MDA I got:
```txt
Traceback (most recent call last):
  File "/project/res/x86_64_RH_6/share/ert/release/gui-test/python/ert_gui/simulation/simulation_panel.py", line 102, in runSimulation
    arguments = self.getSimulationArguments()
  File "/project/res/x86_64_RH_6/share/ert/release/gui-test/python/ert_gui/simulation/simulation_panel.py", line 92, in getSimulationArguments
    return simulation_widget.getSimulationArguments()
  File "/project/res/x86_64_RH_6/share/ert/release/gui-test/python/ert_gui/simulation/multiple_data_assimilation_panel.py", line 106, in getSimulationArguments
    "target_case": self._target_case_model.getValue(),
AttributeError: 'MultipleDataAssimilationPanel' object has no attribute '_target_case_model'
```

Line 106 in `multiple_data_assimilation_panel.py` must be changed to:
`"target_case": self._target_case_format_model.getValue(),`

**Comment by joakim-hove** [comment]
Closing this; go back to original PR: https://github.com/Ensembles/ert/pull/1158

**Pull request closed without merging**
