### PR TITLE
Cherry pick 862

### PR DESCRIPTION
**Pull request by joakim-hove**

### CODE REVIEW

**Comment by GitPaean** [comment]
This PR causes some compiling problem for me for both ERT and OPM-parser. The problem is actually the same. 

When I cmake ERT with ``` cmake ../devel -DBUILD_PYTHON=ON -DBUILD_APPLICATIONS=ON ```

The problem looks like the following:

 ``` ../../lib/x86_64-linux-gnu/libert_util.so.1.0: undefined reference to `pthread_yield_np'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/grdecl_test.x] Error 1
make[1]: *** [libecl/applications/CMakeFiles/grdecl_test.x.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../../lib/x86_64-linux-gnu/libert_util.so.1.0: undefined reference to `pthread_yield_np'
collect2: error: ld returned 1 exit status
../../lib/x86_64-linux-gnu/libert_util.so.1.0: undefined reference to `pthread_yield_np'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/grid_dump_ascii.x] Error 1
make[1]: *** [libecl/applications/CMakeFiles/grid_dump_ascii.x.dir/all] Error 2
../../lib/x86_64-linux-gnu/libert_util.so.1.0: undefined reference to `pthread_yield_np'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/grdecl_grid] Error 1
make[1]: *** [libecl/applications/CMakeFiles/grdecl_grid.dir/all] Error 2
../make[2]: ../lib/*** [bin/grid_dump.x] Error 1
x86_64-linux-gnu/libert_util.so.1.0: undefined reference to `pthread_yield_np'
collect2: error: ld returned 1 exit status
make[1]: *** [libecl/applications/CMakeFiles/grid_dump.x.dir/all] Error 2
make[2]: *** [bin/grid_info.x] Error 1
make[1]: *** [libecl/applications/CMakeFiles/grid_info.x.dir/all] Error 2
../../lib/x86_64-linux-gnu/libert_util.so.1.0: undefined reference to `pthread_yield_np'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/kw_extract.x] Error 1
make[1]: *** [libecl/applications/CMakeFiles/kw_extract.x.dir/all] Error 2
Linking C executable ../../bin/esummary.x
../../lib/x86_64-linux-gnu/libert_util.so.1.0: undefined reference to `pthread_yield_np'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/convert.x] Error 1
make[1]: *** [libecl/applications/CMakeFiles/convert.x.dir/all] Error 2
../../lib/x86_64-linux-gnu/libert_util.so.1.0: undefined reference to `pthread_yield_np'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/esummary.x] Error 1
make[1]: *** [libecl/applications/CMakeFiles/esummary.x.dir/all] Error 2
```

**Comment by babrodtk** [comment]
I can confirm the linker problems reported by GitPaean when ERT is used in OPM-parser. I also get missing references to ```pthread_yield_np```.

**Comment by joakim-hove** [comment]
Sorry - fix coming.

**Comment by joakim-hove** [comment]
OK - try now?

**Comment by GitPaean** [comment]
The compilation of ERT and OPM-parser works fine now. Thanks.

**Pull request merged**
