### PR TITLE
Remove CWrapper from enkf part 3

### PR DESCRIPTION
**Pull request by pgdr**
Slowly cleaning up legacy wraps:
* analysis_config, hook_manager, local_config
* whitespace insanity
* local_config, local_ministep, etc
* **lots more** (see commit log)

This depends on #1323.

### CODE REVIEW

**Comment by pgdr** [comment]
this is now ready for review

**Comment by pgdr** [comment]
Apparently not completely ready after all ... 
`python.tests.ert.server.simulation_context failed`

Perhaps some mistake in a `def free(self)`?

```
path_fmt_alloc_file(..)
enkf_fs_fsync(..)
enkf_fs_decref(..)
enkf_main_free(..)
ert_test_context_free(..)
ffi_call_unix64(..)
ffi_call(..)
_ctypes_callproc(..)
```

**Comment by pgdr** [comment]
Furthermore, 
```
1/1 Test #184: python.tests.core.util.cstring ...***Timeout   3.01 sec
0% tests passed, 1 tests failed out of 1
```

**Comment by pgdr** [comment]
```patch
diff --git a/python/python/ert/enkf/run_arg.py b/python/python/ert/enkf/run_arg.py
index 5547365..6a8735d 100644
--- a/python/python/ert/enkf/run_arg.py
+++ b/python/python/ert/enkf/run_arg.py
@@ -29,8 +29,8 @@ class RunArg(BaseCClass):
         raise NotImplementedError("Cannot instantiat RunArg directly!")
 
     @classmethod
-    def createEnsembleExperimentRunArg(cls, fs, iens, runpath, iter=0):
-        return self._alloc_ENSEMBLE_EXPERIMENT(fs, iens, iter, runpath)
+    def createEnsembleExperimentRunArg(cls, fs, iens, runpath, iter_=0):
+        return cls._alloc_ENSEMBLE_EXPERIMENT(fs, iens, iter_, runpath)
 
     def free(self):
         self._free()
```

**Comment by pgdr** [comment]
Something hangs
```
	138 - enkf_fs (Timeout)
	168 - python.tests.core.cwrap (Timeout)
	172 - python.tests.core.cwrap.metacwrap (Timeout)
	184 - python.tests.core.util.cstring (Timeout)
```

**Comment by joakim-hove** [comment]
I have only looked briefly at the PR itself, but at a glance it looks ok. Regarding your comments:

1. The `_free` bindings look OK.
2. The inline diff for `run_arg.py` obviously looks correct.
3. The travis failure might be consistent with the bug in `run_arg.py`.

**Comment by joakim-hove** [comment]
Now #chess

**Comment by pgdr** [comment]
Thanks, Joakim, however, the timeouts remain even after fixing the `run_arg` ... I'll look more at it tomorrow.

**Comment by pgdr** [comment]
Fixed a bug, now the tests should go through.

**Comment by pgdr** [comment]
```
100% tests passed, 0 tests failed out of 304
Label Time Summary:
Python         = 573.90 sec
StatoilData    =   0.00 sec
```

**Comment by joakim-hove** [comment]
Very good! I have fired off the internal build test as well; will look briefly through the commits.

**Comment by pgdr** [comment]
It's green!  Incoming!

**Comment by joakim-hove** [comment]
:smile:

**Pull request merged**
