### PR TITLE
Eclipse point containment for concave cells

### PR DESCRIPTION
**Pull request by markusdregi**
The work of this PR is twofold. First, we develop a synthetic grid generator that can create much more evil grids then the current EclGrid.createRectangular. Among others, one can create grids with:

- cells formed as trapezoids,
- cells that are concave,
- cells with overlapping corners,
- faults and
- numerous variations of non-parallel pillars.

We also reimplemented the containment test to handle concave cells and the generator described above is used to test this new code. The point containment test is now done as follows:
 - we decompose the cell into 5 carefully selected tetrahedrons according to the decomposition method
of the faces,
 - after which we test for containment in these 5 tetrahedrons by standard techniques.

### CODE REVIEW

**Comment by joakim-hove** [comment]
> The volume of an Eclipse grid cell can be approximated in the following manner

ehhh yes - but why? I don't really understand the purpose of this PR?

**Comment by markusdregi** [comment]
Ah, maybe I was not clear enough. The main purpose is to ensure that the computation of cell volume and point containment is consistent. Hence, the added tests that approximates the volume via the point containment.

The tests fails for non-convex cells and hence this should be fixed. Right now, it also fails for trapezoidal cells, i.e. layers that looks like waves. But this will be ok when the cell_contains_faces branch is merged.

**Comment by joakim-hove** [comment]
>Ah, maybe I was not clear enough. The main purpose is to ensure that the computation of cell volume and point containment is consistent.

OK - but is that even a goal; or realistic - for cells where some of the tetrahedrons contribute with negative volume?

**Comment by pgdr** [comment]
>> ensure that the computation of cell volume and point containment is consistent.

> OK - but is that even a goal;

Obviously yes!

> or realistic - for cells where some of the tetrahedrons contribute with negative volume?

Some _tetrahedrons_ might contribute negatively, but a _cell_ should never have a negative volume, and thus if we compute cell volumes and cell containments based on _cells_ it sounds realistic.

**Comment by joakim-hove** [comment]
OK - this looks good (or frankly - I am not really up to reviewing it). My only wish is that new - quite advanved - functionality for creating grids be split into a separate fully static class - e.g. `GridGenerator`.

**Comment by markusdregi** [comment]
@joakim-hove There is now an EclGridGenerator.

**Pull request merged**
