### PR TITLE
Control verbose flag with environment variable

### PR DESCRIPTION
**Pull request by arielalmendral**
Here is the ERT_VERBOSE variable, related to #918.

Maybe the verbosity should be part of a logging system...

### CODE REVIEW

**Comment by arielalmendral** [comment]
Default false done and tested.

**Comment by joakim-hove** [comment]
Good - I am sorry to be so anal; now you are only missing the entry in 'release-notes.txt':
```txt
[Feature]  Set the the verbose flag from the environment variable ERT_VERBOSE.
```

**Comment by arielalmendral** [comment]
Ahh, sorry, I thougth you were adding the release-notes. Sure that you want to have it under devel and not under docs?

**Comment by joakim-hove** [comment]
> Sure that you want to have it under devel and not under docs?

Well I agree - `docs/` is better.

**Comment by jepebe** [comment]
I am giving my vote for having it at the root. Easily accessible from the Ensmbles/ert front page.

**Comment by joakim-hove** [comment]
> I am giving my vote for having it at the root. Easily accessible from the
> Ensmbles/ert front page.
>

OK - JeanPaul is stronger; at the *real root* - i.e. outside of devel/ as
well.

**Pull request merged**
